---

#- name: "delete keycloak custom resource"
#  k8s:
#    state: absent
#    kind: Keycloak
#    api_version: k8s.keycloak.org/v2alpha1
#    name: rhsso
#    namespace: "{{ namespace }}"

- name: "delete nfd operator in {{ nfd_operator_namespace }}"
  import_role:
    name: ../roles/operator_olm
    tasks_from: uninstall
  vars:
    operator_name: nfd
    subscription_namespace: "{{ nfd_operator_namespace }}"
    subscription_name: "{{ nfd_operator_subscription_name }}"
    csv_prefix: "{{ nfd_operator_csv_prefix }}"
  when: undeploy_nfd_operator is defined and undeploy_nfd_operator == "true"
