---

- set_fact:
    namespace: "{{ gputest_namespace }}"
    resources_dir: "{{ resources_base_dir }}/gputest"
    work_dir_name: gputest
- include_role:
    name: ../roles/gputest
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"


- include_role:
    name: ../roles/gputest
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
