---

- name: "create imagestream in the {{ namespace }} project"
  kubernetes.core.k8s:
    state: present
    kind: ImageStream
    definition: "{{ lookup('template', 'templates/' + binary_imagestream_template) | from_yaml }}"
    namespace: "{{ namespace }}"

- set_fact:
    application_image_tag: "{{ service_image_tag }}"

- name: "deploy {{ application_name }} application in {{ namespace }}"
  kubernetes.core.k8s:
    state: present
    kind: DeploymentConfig
    api_version: apps.openshift.io/v1
    definition: "{{ lookup('template', 'templates/' + application_template ) | from_yaml }}"
    namespace: "{{ namespace }}"

# In AWS, download of quay.io/modh/cuda-notebooks can take close to 4 minutes.  Subsequently, will bump up retries in this task.
- name: "{{ namespace }}: wait until DC {{ application_name }} is ready"
  shell: "{{ openshift_cli }} get dc {{ application_name }} -o template --template={{ json_template }} -n {{ namespace }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 20
  delay: 30
  changed_when: false
