---

- name: "Uninstall AWS based machineset with name {{ infrastructure_id }}-{{ aws_role }}-{{ aws_zone }} in {{ machineset_namespace }}"
  when: undeploy_gpu_machineset is defined and undeploy_gpu_machineset|bool == True
  block:
    - kubernetes.core.k8s_info:
        kind: infrastructure
        api_version: config.openshift.io/v1
        name: cluster
      register: i_response
    - set_fact:
        infrastructure_id: "{{ i_response.resources[0].status.infrastructureName }}"
    
    - kubernetes.core.k8s_info:
        kind: machineset
        api_version: machine.openshift.io/v1beta1
        namespace: "{{ machineset_namespace }}"
      register: m_response
    - set_fact:
        ami_id: "{{ m_response.resources[0].spec.template.spec.providerSpec.value.ami.id }}"
        aws_region: "{{ m_response.resources[0].spec.template.spec.providerSpec.value.placement.region }}"
        aws_zone: "{{ m_response.resources[0].spec.template.spec.providerSpec.value.placement.availabilityZone }}"
        subnet: "{{ m_response.resources[0].spec.template.spec.providerSpec.value.subnet.filters[0]['values'][0] }}"
    
    - k8s:
        state: absent
        kind: machineset
        api_version: machine.openshift.io/v1beta1
        namespace: "{{ machineset_namespace }}"
        name: "{{ infrastructure_id }}-{{ aws_role }}-{{ aws_zone }}"
        wait: true
   
