apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ infrastructure_id }}
  name: {{ infrastructure_id }}-{{ aws_role }}-{{ aws_zone }}
  namespace: {{ machineset_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ infrastructure_id }}
      machine.openshift.io/cluster-api-machineset: {{ infrastructure_id }}-{{ aws_role }}-{{ aws_zone }} 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ infrastructure_id }} 
        machine.openshift.io/cluster-api-machine-role: {{ aws_role }} 
        machine.openshift.io/cluster-api-machine-type: {{ aws_role }} 
        machine.openshift.io/cluster-api-machineset: {{ infrastructure_id }}-{{ aws_role }}-{{ aws_zone }} 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/{{ aws_role }}: "" 
      providerSpec:
        value:
          ami:
            id: {{ ami_id }}
          apiVersion: {{ aws_api_spec_version }}
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ infrastructure_id }}-worker-profile 
          instanceType: {{ aws_instance_type }}
          kind: AWSMachineProviderConfig
          placement:
            region: {{ aws_region }}
            availabilityZone: {{ aws_zone }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ infrastructure_id }}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ subnet }} 
          tags:
            - name: kubernetes.io/cluster/{{ infrastructure_id }} 
              value: owned
          userDataSecret:
            name: worker-user-data

