---

- name: "uninstall clusterpolicy resource in {{ gpu_operator_namespace }}"
  k8s:
    state: absent
    api_version: nvidia.com/v1
    kind: ClusterPolicy
    name: gpu-cluster-policy
    namespace: "{{ gpu_operator_namespace }}"
    wait: true

- name: "delete NVidea GPU operator in {{ gpu_operator_namespace }}"
  import_role:
    name: ../roles/operator_olm
    tasks_from: uninstall
  vars:
    operator_name: nvidia_gpu
    subscription_namespace: "{{ gpu_operator_namespace }}"
    subscription_name: "{{ nvidia_gpu_operator_subscription_name }}"
    csv_prefix: "{{ nvidia_gpu_operator_csv_prefix }}"
  when: uninstall_nvidia_gpu_operator is defined and uninstall_nvidia_gpu_operator == "true"
